### ISSUE TITLE
Resource identifier objects in relationships array should be sorted

### ISSUE THREAD

**Issue by vesauimonen** [kvesteri/sqlalchemy-json-api#10]
The resource identifier objects in a resource object's relationship array are not sorted by id:

``` python
query = query_builder.select(Post, fields={'posts': ['comments']})

db.session.execute(query).scalar()['data'][0]['relationships']['comments']['data']

# [
#     {'id': '0fc71c71-50c3-4151-9f07-a0b430eded0e', 'type': 'comments'},
#     {'id': 'e4084592-eb4e-4590-88a5-98f44530bbba', 'type': 'comments'},
#     {'id': '1e37dee3-167d-4d8a-b9ac-457aebcc9d93', 'type': 'comments'},
#     {'id': '44cb8206-ef12-4b3a-bee6-84c44a08bfc0', 'type': 'comments'},
# ]
```

While JSON API 1.0 specification does not require ordering, the array should be sorted to guarantee deterministic results.

**Comment by vesauimonen** [comment]
The fix for this actually broke my `query_builder.select(…)`. This is due to the fact that the resource identifier objects in the relationship array have a `hybrid_property` id consisting of two foreign keys:

``` python
@hybrid_property
def id(self):
    return '{0}:{1}'.format(self.fk1, self.fk2)

@id.expression
def id(cls):
    return db.func.concat(cls.fk1, db.text("':'"), cls.fk2).label('id')
```

Now the `ORDER BY id` will raise:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column reference "id" is ambiguous
```

**Comment by kvesteri** [comment]
https://bitbucket.org/zzzeek/sqlalchemy/issues/3882/order-by-inspection-sometimes-returns
