### ISSUE TITLE
Hardcoded PK column name

### ISSUE THREAD

**Issue by sergeyromanov** [kvesteri/sqlalchemy-json-api#2]
Hi!

I was looking into using your module and tried to set it up according to [Quickstart page](http://sqlalchemy-json-api.readthedocs.org/en/latest/quickstart.html). However, I'm getting an exception:

```
Couldn't find 'id' property for model ...
```

It seems that the library always expects PK column to be named `id`, whereas I have `user_id`.

**Comment by kvesteri** [comment]
[JSON API spec](http://jsonapi.org/) expects all resources to be identified by a field named `id`.
