### ISSUE TITLE
Does sqlalchemy-json-api conform to the JSON API 1.0 stable spec?

### ISSUE THREAD

**Issue by jesselang** [kvesteri/sqlalchemy-json-api#3]
This project looks really useful. I'm considering it for use in a project I'm working on. Does the project support all of the JSON API spec? If not, what parts are and aren't supported? This project seems to be the only one that works with sqla that supports compound documents, which is awesome!  Thanks so much!

**Comment by kvesteri** [comment]
The focus of this package is to support subset of those functionalities. Mainly it is just for optimizing the GET requests response times to the absolute minimum. Our company will release a fully operating framework for JSON API 1.0 spec with Flask + SQLAlchemy in the next couple of months. You can already see some of the code here: https://github.com/fastmonkeys/flask-jsonapi

The name of the project will probably change as well.

**Comment by jesselang** [comment]
That link didn't work for me. I got a 404 not found. Sounds like a great project. I'd like to follow the progress and perhaps contribute.

**Comment by kvesteri** [comment]
Oh yeah, just noticed the repo isn't public yet. I'll keep you informed once we publish it.
