### ISSUE TITLE
Datetimes are serialized without milliseconds or timezone information

### ISSUE THREAD

**Issue by vesauimonen** [kvesteri/sqlalchemy-json-api#5]
Currently datetimes are serialized without milliseconds or timezone information, such as:

``` json
{  "created_at": "2014-10-01T07:37:30" }
```

The prefferable serialization would include milliseconds and timezone, such as:

``` json
{  "created_at": "2014-10-01T07:37:30.000000Z" }
```

**Comment by kvesteri** [comment]
Fixed using [type formatters](http://sqlalchemy-json-api.readthedocs.io/en/latest/type_formatting.html).
